var user ={
  "login": "Shane40",
  "id": 10365759,
  "avatar_url": "https://avatars.githubusercontent.com/u/10365759?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Shane40",
  "html_url": "https://github.com/Shane40",
  "followers_url": "https://api.github.com/users/Shane40/followers",
  "following_url": "https://api.github.com/users/Shane40/following{/other_user}",
  "gists_url": "https://api.github.com/users/Shane40/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Shane40/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Shane40/subscriptions",
  "organizations_url": "https://api.github.com/users/Shane40/orgs",
  "repos_url": "https://api.github.com/users/Shane40/repos",
  "events_url": "https://api.github.com/users/Shane40/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Shane40/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Shane Blatt",
  "company": "",
  "blog": "",
  "location": "United States",
  "email": "shane.blatt@yahoo.com",
  "hireable": false,
  "bio": null,
  "public_repos": 15,
  "public_gists": 0,
  "followers": 2,
  "following": 0,
  "created_at": "2015-01-01T17:49:52Z",
  "updated_at": "2015-01-26T18:13:27Z"
}